# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github-Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: CI=false npm run build --if-present

    - name: Commit changes
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      with:
        source_file: 'build/*'
        destination_repo: 'Community-network/Server-manager'
        user_email: 'example@email.com'
        user_name: 'autobuilder'
        commit_message: 'A custom message for the commit'
        destination_branch: 'gh-pages'
      env:
        API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
